apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: sov0zccvr-python 
  janus-idp.io/tekton: sov0zccvr-python
  backstage.io/kubernetes-id: sov0zccvr-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sov0zccvr-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml